### ISSUE TITLE
Create extra package from docs/datacard.py

### ISSUE THREAD

**Issue by hagenw** [audeering/datasets#6]
As we also have a internal project that lists databases,
and it would make it much easier for others to also create data cards,
I would argue that we should create an extra package for creating a data card.
The package should contain all the code from `docs/datacard.py` that is responsible for creating a single data card,
which means leave out the code that lists available databases.

Unfortunately, the name `datacards` for a corresponding Python package [is already taken](https://pypi.org/project/datacards/),
maybe we go with `audbcards`?

@ChristianGeng any other suggestions?

**Comment by ChristianGeng** [comment]
Concerning the name: `audbcards`  is more specific and therefore better -  as the code will only be useful in the context of data handled within  `audb`.  I am happy with this.

**Comment by hagenw** [comment]
> as the code will only be useful in the context of data handled within `audb`

Exactly, this was also my motivation behind the name.

**Comment by hagenw** [comment]
We have created the package at https://github.com/audeering/audbcards
